services:
  postgres:
    image: postgres
    container_name: postgres_container_gop
    environment:
      - "POSTGRES_USER=nine"
      - "POSTGRES_PASSWORD=999"
      - "PGDATA: /data/postgres"
    volumes:
      - postgres:/data/postgres/
    ports:
      - "15432:5432"
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: pgadmin_container_gop
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
    
volumes:
  postgres:
  pgadmin:
